# PermissionsRanks
#      rollbackcmd: undo <player>

onChat:
  RankColorPly: '&a'
  RankColorWht: '&7'
  RankColorCre: '&e'
  RankColorMod: '&9' 
  RankColorAdm: '&c'
  RankColorOps: '&c'
onBan:
  RollbackComd: 
Version:
  ConfigYMLVer: 1