# PermissionsRanks
#      rollbackcmd: undo <player>

onChat:
  RankColorPly: '&a<player>&a'
  RankColorWht: '&7<player>&7'
  RankColorCre: '&e<player>&e'
  RankColorMod: '&9<player>&9' 
  RankColorAdm: '&c<player>&c'
  RankColorOps: '&8<player>&8'
onBan:
  RollbackComd: 
Version:
  ConfigYMLVer: 2